package com.jovian.navigation

import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.navigation.NavController
import androidx.navigation.fragment.findNavController
import com.jovian.navigation.databinding.FragmentLoginBinding


class LoginFragment : Fragment() {

    lateinit var binding: FragmentLoginBinding

    var navController: NavController? = null


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        binding = FragmentLoginBinding.inflate(inflater,container,false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        //We obtain the NavController through findNavigation
        //navController is  defined as member variable of the fragment
        navController = findNavController()

        binding.btnLoginNext.setOnClickListener {
            //Navigates to InfoFragment

            //Get info from UI EditText
            val login = Login()
            login.usr = binding.etUser.text.toString()
            login.pass = binding.etPass.text.toString()

            //Creating the action object
            val action = LoginFragmentDirections //This class is autogenerated with safeargs plugin
                .actionLoginFragmentToInfoFragment(login)
            //navController.navigate(R.id.action_loginFragment_to_infoFragment)
            //replace by:
            navController!!.navigate(action)
        }
    }
}